### ISSUE TITLE
NBT tag isn't getting transferred to villager sale

### ISSUE THREAD

**Issue by AnvilPuncher** [DoubleDoorDevelopment/InsiderTrading#3]
Hi,

The NBT tag is not being written correctly to the items being traded.  The configuration file has the tag and it makes sense but the Villager doesn't have this tag transferred to the Villager's NBT data that holds the Offers information.  Consequently, the Villager doesn't trade for an item that has NBT tag data but only trades for the item without the desired name or enchantments and so forth.  

Thank you

**Comment by Claycorp** [comment]
This wasn't fixed as it's a vanilla issue. If you wish to have villagers stick to NBT/Meta in the input slots use this: http://minecraft.curseforge.com/projects/villagermetafix?gameCategorySlug=mc-mods&projectID=242057

Blame vanilla.... Insider trading will not fix this on its own.
